version: "3.9"
services:
  scraper:
    build: amazon-scraping-service/.
    ports:
      - "8080:8080"
  persister:
    build: amazon-scraping-persistence-service/.
    ports:
      - "8081:8081"
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoDB
      MONGO_INITDB_ROOT_PASSWORD: mongoDB
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container: